#!/bin/bash

set -e

if [ ! -f /tmp/build-dsd-fw2 ]
then
    echo 'no firewall yet'
    sudo iptables -I INPUT 2 -i lo -p tcp --dport 8002 -j ACCEPT
    touch /tmp/build-dsd-fw2

else
    echo 'firewall in place'


fi


#todo copy a secrets directory and fail if it does not exist (could be param with environment name, staging live etc)






docker build -t django-site-docker-hcccm .


firefox http://127.0.0.1:8002/

docker-compose up --build

