# Pull base image
FROM python:3.8

# set environment variables

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory

WORKDIR /code

# Install dependencies

COPY Pipfile Pipfile.lock requirements.txt /code/

RUN pip install pipenv && pipenv install --system
#RUN pip install -r /code/requirements.txt
RUN pip install django==3.1.14

# Copy project

COPY . /code/
